# Generated by Django 3.2.4 on 2021-06-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approve_comment',
            field=models.BooleanField(default=False),
        ),
    ]
